---
kind: pipeline
type: kubernetes
name: default

steps:
- name: preview
  image: pulumi/pulumi:latest
  commands:
    - npm install
    - pulumi preview --stack digitalocean --non-interactive
  when:
    event:
      include:
        - pull_request
